# Generated by Django 5.1 on 2024-08-26 07:00

from django.db import migrations
from django.utils import timezone
import random


def create_initial_data(apps, schema_editor):
    Team = apps.get_model('football_management', 'Team')
    Player = apps.get_model('football_management', 'Player')
    Coach = apps.get_model('football_management', 'Coach')
    PlayerTeam = apps.get_model('football_management', 'PlayerTeam')
    CoachTeam = apps.get_model('football_management', 'CoachTeam')

    # Teams data
    teams_data = [
        ("Manchester United", "Old Trafford", "CLUB", 1878, "England"),
        ("Real Madrid", "Santiago Bernabéu", "CLUB", 1902, "Spain"),
        ("Bayern Munich", "Allianz Arena", "CLUB", 1900, "Germany"),
        ("Paris Saint-Germain", "Parc des Princes", "CLUB", 1970, "France"),
        ("Juventus", "Allianz Stadium", "CLUB", 1897, "Italy"),
        ("Italy", "Allianz Stadium", "NATIONAL", 1911, "Italy"),
    ]

    teams = []
    for name, stadium, team_type, founded, country in teams_data:
        team = Team.objects.create(
            name=name,
            home_stadium=stadium,
            team_type=team_type,
            founded_year=founded,
            country=country
        )
        teams.append(team)

    players_data = [
        ("Cristiano", "Ronaldo", "Portugal", 7),
        ("Lionel", "Messi", "Argentina", 10),
        ("Robert", "Lewandowski", "Poland", 9),
        ("Kylian", "Mbappé", "France", 7),
        ("Erling", "Haaland", "Norway", 9),
        ("Neymar", "Jr.", "Brazil", 10),
        ("Kevin", "De Bruyne", "Belgium", 17),
        ("Virgil", "van Dijk", "Netherlands", 4),
        ("Harry", "Kane", "England", 9),
        ("Mohamed", "Salah", "Egypt", 11),
        ("Bruno", "Fernandes", "Portugal", 18),
        ("Trent", "Alexander-Arnold", "England", 66),
        ("Joshua", "Kimmich", "Germany", 6),
        ("Karim", "Benzema", "France", 9),
        ("Sadio", "Mané", "Senegal", 10),
        ("Thibaut", "Courtois", "Belgium", 1),
        ("Rúben", "Dias", "Portugal", 3),
        ("Son", "Heung-min", "South Korea", 7),
        ("Jude", "Bellingham", "England", 22),
        ("Federico", "Valverde", "Uruguay", 15),
        ("Alphonso", "Davies", "Canada", 19),
        ("Jamal", "Musiala", "Germany", 42),
        ("Phil", "Foden", "England", 47),
        ("Vinícius", "Júnior", "Brazil", 20),
        ("Pedri", "González", "Spain", 16),
        ("Gianluigi", "Donnarumma", "Italy", 99),
        ("Marcus", "Rashford", "England", 10),
        ("Rodri", "Hernández", "Spain", 16),
        ("Bernardo", "Silva", "Portugal", 20),
        ("Bukayo", "Saka", "England", 7)
    ]

    players = []
    for first_name, last_name, nationality, jersey_number in players_data:
        player = Player.objects.create(
            first_name=first_name,
            last_name=last_name,
            date_of_birth=timezone.now().replace(year=random.randint(1985, 2006)),
            nationality=nationality,
            jersey_number=jersey_number,
            height=random.randint(170, 195),
            market_value=random.randint(10000000, 100000000)
        )
        players.append(player)

    coaches_data = [
        ("Pep", "Guardiola", "Spain"),
        ("Jürgen", "Klopp", "Germany"),
        ("Carlo", "Ancelotti", "Italy"),
        ("Thomas", "Tuchel", "Germany"),
        ("Zinedine", "Zidane", "France"),
    ]

    coaches = []
    for first_name, last_name, nationality in coaches_data:
        coach = Coach.objects.create(
            first_name=first_name,
            last_name=last_name,
            date_of_birth=timezone.now().replace(year=random.randint(1960, 1980)),
            nationality=nationality
        )
        coaches.append(coach)

    for team in teams:
        team_players = random.sample(players, 11)
        for player in team_players:
            PlayerTeam.objects.create(
                player=player,
                team=team,
                position=random.choice(
                    ['GK', 'CB', 'LB', 'RB', 'RWB', 'LWB', 'CDM', 'CM', 'CAM', 'LM', 'RM', 'LW', 'RW', 'CF', 'RF', 'LF',
                     'ST'])
            )

        team_coaches = random.sample(coaches, random.randint(1, 3))
        for coach in team_coaches:
            CoachTeam.objects.create(coach=coach, team=team)


def reverse_initial_data(apps, schema_editor):
    Team = apps.get_model('football_management', 'Team')
    Player = apps.get_model('football_management', 'Player')
    Coach = apps.get_model('football_management', 'Coach')
    PlayerTeam = apps.get_model('football_management', 'PlayerTeam')
    CoachTeam = apps.get_model('football_management', 'CoachTeam')

    Team.objects.all().delete()
    Player.objects.all().delete()
    Coach.objects.all().delete()
    PlayerTeam.objects.all().delete()
    CoachTeam.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('football_management', '0004_alter_playerteam_position_delete_playerposition'),
    ]

    operations = [
        migrations.RunPython(create_initial_data, reverse_initial_data),
    ]